// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Zy5LjdJaGlcohgcuf-CpH6znN9G3fGQ',
    appId: '1:542651070691:web:dab71290eb2baa89fb6dd6',
    messagingSenderId: '542651070691',
    projectId: 'tratto-2025',
    authDomain: 'tratto-2025.firebaseapp.com',
    storageBucket: 'tratto-2025.firebasestorage.app',
    measurementId: 'G-V3G1EMEZ7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCimruH_-FxGpZe5PlyEFg3IL87AeoAHjI',
    appId: '1:542651070691:android:816e6fa2042d1941fb6dd6',
    messagingSenderId: '542651070691',
    projectId: 'tratto-2025',
    storageBucket: 'tratto-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBj_bodjZvvbAi0T4RgyHGNESVUEYQXm8',
    appId: '1:542651070691:ios:6cc17f0412a22147fb6dd6',
    messagingSenderId: '542651070691',
    projectId: 'tratto-2025',
    storageBucket: 'tratto-2025.firebasestorage.app',
    iosBundleId: 'com.example.gestaoBelezaApp',
  );
}
